modLoader = "javafml"
loaderVersion = "[43,)"
issueTrackerURL = "https://github.com/Polymeta/Pokegift/issues"
license = "MIT License"

[[mods]]
modId = "pokegift"
version = "${version}"
displayName = "Pokegift"
authors = "Polymeta"
description = '''
Gift your pokemon to players!
'''
#logoFile = ""

[[dependencies.pokegift]]
modId = "forge"
mandatory = true
versionRange = "[47,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.pokegift]]
modId = "minecraft"
mandatory = true
versionRange = "[1.20.1,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.pokegift]]
modId = "architectury"
mandatory = true
versionRange = "[9.1.12,)"
ordering = "AFTER"
side = "BOTH"

[[dependencies.pokegift]]
modId = "cobblemon"
mandatory = true
versionRange = "[1.4.0,)"
ordering = "AFTER"
side = "BOTH"