modLoader = "javafml"
loaderVersion = "[43,)"
issueTrackerURL = "https://github.com/Polymeta/Pokegift/issues"
license = "MIT License"

[[mods]]
modId = "pokegift"
version = "${version}"
displayName = "Pokegift"
authors = "Polymeta"
description = '''
Gift your pokemon to players!
'''
#logoFile = ""

[[dependencies.pokegift]]
modId = "forge"
mandatory = true
versionRange = "[43,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.pokegift]]
modId = "minecraft"
mandatory = true
versionRange = "[1.19.2,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.pokegift]]
modId = "architectury"
mandatory = true
versionRange = "[6.5.69,)"
ordering = "AFTER"
side = "BOTH"

[[dependencies.pokegift]]
modId = "cobblemon"
mandatory = true
versionRange = "[1.3.1,)"
ordering = "AFTER"
side = "BOTH"